
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbXNvanZ2MDkwMDAwdDU3czdyb252eWloIiwiZW1haWwiOiJ0ZXN0NEB0ZXN0LmNvbSIsImlhdCI6MTc4NjQ0NjEwMiwiZXhwIjoxNzg2NTMyNTAyfQ.tbHgVKDd2H1r_B6-7Qa0oILMzUosQYarzCPNzCmt6Jw
GET http://localhost:3000/auth/profile
Authorization: Bearer {{token}}